---
title: "Homework2026-03-1"
author: "曹力文"
date: "2026-03-26"
output: html_document
---
```{r}
#--------------------------
#homework2026-03-1
#author-曹力文
#student number SA24008217
#ade4包里env中部分数据处理
#--------------------------
library(ade4)
library(dplyr)

data("doubs", package = "ade4")
result <- doubs$env |> 
  select(dfs, alt, oxy, pH) |>  
  rename(distance = dfs, oxygen = oxy) |>
  filter(alt > 200) |>
  arrange(desc(alt)) |>
  mutate(oxygen_category = ifelse(oxygen > 90, "High", "Low")) |>
  group_by(oxygen_category) |>
  summarise(mean_alt = mean(alt), 
            mean_pH = mean(pH)/10)  # 原数据pH为10倍整数
result
```
```{r}
#--------------------------
#homework2026-03-2
#author-曹力文
#student number SA24008217
#ade4包里env中部分数据可视化填空题目
#--------------------------
library(ade4)
library(ggplot2)
data("doubs", package = "ade4")

# 第一幅图：x=alt, y=oxy 的散点图
ggplot(data = doubs$env) +
  geom_point(mapping = aes(x = alt, y = oxy))

# 第二幅图：用 dfs（距离）调整颜色
ggplot(data = doubs$env) +
  geom_point(mapping = aes(x = alt, y = oxy, color = dfs))
```